### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by cwarlen-dice** [cwarlen-dice/furima-35518#9]
フリマアプリを作成しましたので、挙動の確認お願いします。
フリマアプリのURL:<https://furima-35518.herokuapp.com/>

Basic認証
ID:admin
パスワード:Rqe2tUDnUnuK

出品者用
メールアドレス:a@a
パスワード:aaa111

購入者用
メールアドレス:q@q
パスワード:aaa111

**Comment by takumi0530** [comment]
@cwarlen-dice さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/119755088-6adec900-bedc-11eb-9c48-6f611ab9d6f9.png)
